version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: stokla
      POSTGRES_PASSWORD: "_Ysr44pRqPfaEIy7VSo94Vw5450gNEdt"
    volumes:
      - stokla_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "p6rk2EZBvXEVQ6c_wOaR1jtrzNHUj5dy"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  stokla_data:
